import { CommandHandler, ICommandHandler } from '@nestjs/cqrs'
import { Inject } from '@nestjs/common'
import { CreateOfferCommand } from '../impl/create-offer.command'
import { OfferRepository } from '../../../domain/repositories/offer.repository'
import { Offer } from '../../../domain/entities/offer'
import { OfferType } from 'src/offers/domain/enums/type.enum'

@CommandHandler(CreateOfferCommand)
export class CreateOfferHandler implements ICommandHandler<CreateOfferCommand> {
  constructor(
    @Inject(OfferRepository)
    private readonly offerRepository: OfferRepository,
  ) {}

  async execute(command: CreateOfferCommand): Promise<any> {
    const { createOfferDto } = command
    const newOffer = new Offer(
      0, // ID will be generated by the database
      createOfferDto.title,
      createOfferDto.content,
      createOfferDto.image,
      createOfferDto.price,
      createOfferDto.city,
      createOfferDto.address,
      createOfferDto.latitude,
      createOfferDto.longitude,
      createOfferDto.type as OfferType,
      createOfferDto.email,
    )

    return this.offerRepository.save(newOffer)
  }
}
